version: "3.8"
services: 
  # app:
  #   image: node:12-alpine3.12
  #   working_dir: /app
  #   volumes: 
  #     - ./:/app
  #   command: sh -c "npm install --production && npm start"
  #   ports: 
  #     - 3000:3000
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgress
         - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata: